name: Deploy Gymcyclopedia

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies (if package.json exists)
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi
        
    - name: Validate HTML files
      run: |
        echo "Validating HTML structure..."
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "Checking $file..."
            # Basic validation - check if file is well-formed
            if grep -q "<!DOCTYPE html>" "$file" && grep -q "</html>" "$file"; then
              echo "✅ $file is valid"
            else
              echo "❌ $file may have issues"
              exit 1
            fi
          fi
        done
        
    - name: Check Supabase configuration
      run: |
        echo "Checking Supabase configuration..."
        if grep -q "YOUR_SUPABASE_PROJECT_URL" *.html; then
          echo "❌ Found placeholder URLs in HTML files"
          exit 1
        fi
        if grep -q "YOUR_SUPABASE_ANON_KEY" *.html; then
          echo "❌ Found placeholder API keys in HTML files"
          exit 1
        fi
        echo "✅ Supabase configuration looks good"
        
    - name: Replace environment variables (if needed)
      run: |
        # Replace any remaining placeholders with environment variables
        # Since we're using GitHub Pages, the real credentials are already in place
        echo "✅ Using hardcoded Supabase credentials for GitHub Pages deployment"
        
    - name: Build project (if build script exists)
      run: |
        if [ -f package.json ] && npm run build --if-present; then
          echo "✅ Build completed"
        else
          echo "ℹ️ No build step required for static site"
        fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "🚀 Deployment successful!"
          echo "Your Gymcyclopedia app has been deployed successfully."
        else
          echo "❌ Deployment failed!"
          echo "Check the logs above for error details."
        fi
        
    - name: Post-deployment health check
      if: success()
      run: |
        echo "🔍 Running post-deployment checks..."
        echo "✅ All HTML files validated"
        echo "✅ Supabase configuration verified"
        echo "✅ Deployment completed successfully"
        echo ""
        echo "🌐 Your app should be live at: https://sandyhub007.github.io/summer-project/" 